### ISSUE TITLE
Observing FATAL Error with "JavaScript heap out of memory" and MWDI got stopped

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#1049]
Enabled Device-attribute-value-change subscription on 2024-11-12T04:15:21 CET, MWDI got crashed on 2024-11-14T14:30 CET with below prints
Version:1.1.2.g

Error Print:
```
[14.11.2024 15:30.26.457] [LOG]   recordServiceRequest - record service request with body {} failed with error: Too many pending tasks in queue ./database/load.json
[14.11.2024 15:30.26.668] [LOG]
 callback : http://x.x.x.x:xxxx/rests/data/network-topology:network-topology/topology=topology-netconf/node=121254731/yang-ext:mount/core-model-1-4:control-construct header :{"Authorization":"Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}body :""response code:200
[14.11.2024 15:30.27.857] [LOG]   Error: Too many pending tasks in queue ./database/load.json
    at AsyncLock.acquire (/home/openbackhaul/microWaveDeviceInventory/node_modules/async-lock/lib/index.js:195:15)
    at Object.exports.readFromDatabaseAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/databaseDriver/JSONDriver.js:27:23)
    at Function.getLogicalTerminationPointListAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/ControlConstruct.js:32:59)
    at Function.getOperationServerUuidAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/layerProtocols/OperationServerInterface.js:197:13)
    at Function.createResponseHeader (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/rest/server/ResponseHeader.js:64:70)
    at /home/openbackhaul/microWaveDeviceInventory/controllers/IndividualServices.js:1596:51
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

<--- Last few GCs --->

[1:0x664d0e0] 3037195745 ms: Scavenge (reduce) 1995.0 (2037.4) -> 1994.0 (2037.4) MB, 10.0 / 0.0 ms  (average mu = 0.397, current mu = 0.405) allocation failure
[1:0x664d0e0] 3037195820 ms: Scavenge (reduce) 1995.0 (2037.4) -> 1994.0 (2037.4) MB, 8.5 / 0.0 ms  (average mu = 0.397, current mu = 0.405) allocation failure
[1:0x664d0e0] 3037195885 ms: Scavenge (reduce) 1995.0 (2037.4) -> 1994.2 (2037.4) MB, 11.4 / 0.0 ms  (average mu = 0.397, current mu = 0.405) allocation failure


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb090e0 node::Abort() [node]
 2: 0xa1b70e  [node]
 3: 0xce1a20 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xce1dc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe99435  [node]
 6: 0xe99f16  [node]
 7: 0xea843e  [node]
 8: 0xea8e80 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xeabd75 v8::internal::Heap::HandleGCRequest() [node]
10: 0xe39417 v8::internal::StackGuard::HandleInterrupts() [node]
11: 0xf92bd5 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
12: 0xf974c1 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
13: 0xf95410 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
14: 0xf94845 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
15: 0xf94845 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
16: 0xf974c1 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
17: 0xf95410 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
18: 0xf974c1 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
19: 0xf95410 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
20: 0xf974c1 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
21: 0xf95410 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
22: 0xf974c1 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
23: 0xf98ddf v8::internal::JsonStringify(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
24: 0xd63c87 v8::internal::Builtin_JsonStringify(int, unsigned long*, v8::internal::Isolate*) [node]
25: 0x15d9f39  [node]
```

**Comment by Ziabatcha** [comment]
Issue not observed, hence closing it.
