### ISSUE TITLE
[Performance] Observing 500 response code when bulk controller-attribute-value-change notifications triggered from controller

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#1053]
When user stop the mediator which is holding 3200 connected devices, controller start to send 3200 controller-attribute-value-change notification to NP -> MWDI. 
But observed error in MWDI as shown below 
Package:1.1.2.g
```
2024-11-22T16:47:53.471136451Z [22.11.2024 16:47.53.378] [LOG]   Updating device list into cache...
2024-11-22T16:47:53.471159711Z [22.11.2024 16:47.53.385] [LOG]   TypeError: Cannot read properties of undefined (reading 'took')
2024-11-22T16:47:53.471163441Z     at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:10421:18
2024-11-22T16:47:53.471166711Z     at runMicrotasks (<anonymous>)
2024-11-22T16:47:53.471170450Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-11-22T16:47:53.471173590Z [22.11.2024 16:47.53.398] [LOG]   Error: Too many pending tasks in queue ./database/load.json
2024-11-22T16:47:53.471176890Z     at AsyncLock.acquire (/home/openbackhaul/microWaveDeviceInventory/node_modules/async-lock/lib/index.js:195:15)
2024-11-22T16:47:53.471180130Z     at Object.exports.readFromDatabaseAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/databaseDriver/JSONDriver.js:27:23)
2024-11-22T16:47:53.471183530Z     at Function.getLogicalTerminationPointListAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/ControlConstruct.js:32:59)
2024-11-22T16:47:53.471186970Z     at Function.getOperationServerUuidAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/layerProtocols/OperationServerInterface.js:197:13)
2024-11-22T16:47:53.471190630Z     at Function.createResponseHeader (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/rest/server/ResponseHeader.js:64:70)
2024-11-22T16:47:53.471194001Z     at /home/openbackhaul/microWaveDeviceInventory/controllers/IndividualServices.js:2802:51
2024-11-22T16:47:53.471197701Z     at runMicrotasks (<anonymous>)
2024-11-22T16:47:53.471201101Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-11-22T16:47:53.471204341Z     at runNextTicks (node:internal/process/task_queues:65:3)
2024-11-22T16:47:53.471207361Z     at listOnTimeout (node:internal/timers:528:9)
2024-11-22T16:47:53.471210541Z [22.11.2024 16:47.53.399] [LOG]   recordServiceRequest - record service request with body {} failed with error: Too many pending tasks in queue ./database/load.json
2024-11-22T16:47:53.471213841Z POST /v1/regard-controller-attribute-value-change 500 91990.760 ms - 55
2024-11-22T16:47:53.471217351Z [22.11.2024 16:47.53.400] [LOG]   TypeError: Cannot read properties of undefined (reading 'took')
2024-11-22T16:47:53.471220451Z     at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:10421:18
2024-11-22T16:47:53.471226341Z     at runMicrotasks (<anonymous>)
2024-11-22T16:47:53.471229471Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-11-22T16:47:53.471232411Z [22.11.2024 16:47.53.401] [LOG]   Error: Too many pending tasks in queue ./database/load.json
2024-11-22T16:47:53.471235451Z     at AsyncLock.acquire (/home/openbackhaul/microWaveDeviceInventory/node_modules/async-lock/lib/index.js:195:15)
2024-11-22T16:47:53.471238621Z     at Object.exports.readFromDatabaseAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/databaseDriver/JSONDriver.js:27:23)
2024-11-22T16:47:53.471241931Z     at Function.getLogicalTerminationPointListAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/ControlConstruct.js:32:59)
2024-11-22T16:47:53.471245371Z     at Function.getOperationServerUuidAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/layerProtocols/OperationServerInterface.js:197:13)
2024-11-22T16:47:53.471248811Z     at Function.createResponseHeader (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/rest/server/ResponseHeader.js:64:70)
2024-11-22T16:47:53.471252261Z     at /home/openbackhaul/microWaveDeviceInventory/controllers/IndividualServices.js:2802:51
2024-11-22T16:47:53.471255551Z     at runMicrotasks (<anonymous>)
2024-11-22T16:47:53.471258481Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-11-22T16:47:53.471262131Z     at runNextTicks (node:internal/process/task_queues:65:3)
2024-11-22T16:47:53.471265161Z     at listOnTimeout (node:internal/timers:528:9)
2024-11-22T16:47:53.471268141Z [22.11.2024 16:47.53.401] [LOG]   recordServiceRequest - record service request with body {} failed with error: Too many pending tasks in queue ./database/load.json
2024-11-22T16:47:53.471271511Z POST /v1/regard-controller-attribute-value-change 500 91898.040 ms - 55
2024-11-22T16:47:53.471274951Z [22.11.2024 16:47.53.402] [LOG]   TypeError: Cannot read properties of undefined (reading 'took')
2024-11-22T16:47:53.471278020Z     at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:10421:18
2024-11-22T16:47:53.471281211Z     at runMicrotasks (<anonymous>)
2024-11-22T16:47:53.471284311Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-11-22T16:47:53.471424941Z POST /v1/regard-controller-attribute-value-change 500 104786.404 ms - 55
2024-11-22T16:47:53.471437661Z [22.11.2024 16:47.53.407] [LOG]   TypeError: Cannot read properties of undefined (reading 'took')
2024-11-22T16:47:53.471441991Z     at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:10421:18
2024-11-22T16:47:53.471445211Z     at runMicrotasks (<anonymous>)

```

**Comment by ssomasundara** [comment]
@SIAE team: Pls update the root cause and the solution applied for the issue.

**Comment by latta-siae** [comment]
This error is misleading.
Actually MWDI is writing information in ELK correct, but in order to print log, code is referencing to "undefined" properties, then exception happens.
So that despite data are stored, it return an error.
For MATR app that will trigger a retry. This is causing delay on operation
