### ISSUE TITLE
1.1.2i: MWDI Cache is not getting updated for device avc

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#1060]
When we try to change any attribute value via Controller, Notification proxy receives the notification.  But MWDI cache is not getting updated properly. 

When tried to retrieve the mwdi cache for that particular equipment, its still reflects the older value.
Live and Cache differs.

MWDI Package : 1.1.2i
 
MWDI Logs:
 
[13.12.2024 04:11.17.324] [LOG]   loggingErrorHandler - caught error, returning response with status code "404" and body {"code":404,"message":"not found","errors":[{"path":"/v1/regard-attribute-value-change","message":"not found"}]}

POST /v1/regard-attribute-value-change 404 11.283 ms - 154

[13.12.2024 04:11.17.333] [ERROR] Error: Request failed with status code 404

    at createError (/home/openbackhaul/microWaveDeviceInventory/node_modules/axios/lib/core/createError.js:16:15)

    at settle (/home/openbackhaul/microWaveDeviceInventory/node_modules/axios/lib/core/settle.js:17:12)

    at IncomingMessage.handleStreamEnd (/home/openbackhaul/microWaveDeviceInventory/node_modules/axios/lib/adapters/http.js:269:11)

    at IncomingMessage.emit (node:events:525:35)

    at endReadableNT (node:internal/streams/readable:1358:12)

    at processTicksAndRejections (node:internal/process/task_queues:83:21) {

  config: {

    url: 'HTTP://172.28.127.11:3008/v1/regard-attribute-value-change',

    method: 'post',

    data: '{"MicroWaveDeviceInventory-1-1:attribute-value-changed-notification":{"counter":104,"timestamp":"2024-12-13T04:43:50.0+00:00","attribute-name":"interface-name","new-value":"Test9876"}}',

**Comment by latta-siae** [comment]
regard-attribute-value-change api is not implemented.
are you sure that you are triggering the right api?

**Comment by latta-siae** [comment]
> Hi [@latta-siae](https://github.com/latta-siae) , Is Device AVC not supported in 1.1.2.j_build ? This API was working earlier and got degraded recently in MWDI Package : 1.1.2i for which issue [#1060](https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/1060) was reported.

That is weird.
I didn't touch anything on the code. In which build the issue appear?
I'm going back through git history in order to understand what has been changed.

**Comment by latta-siae** [comment]
According on load.json this service isn't implemented in MWDI but in **HistoricalMicroWaveDeviceInventory**

```
{
          "uuid": "mwdi-1-0-0-http-c-hmwdi-1-0-0-100",
          "ltp-direction": "core-model-1-4:TERMINATION_DIRECTION_SINK",
          "client-ltp": [
            "mwdi-1-0-0-op-c-is-hmwdi-1-0-0-100",
            "mwdi-1-0-0-op-c-is-hmwdi-1-0-0-101",
            "mwdi-1-0-0-op-c-is-hmwdi-1-0-0-102"
          ],
```

there are 3 services:
- ```/v1/regard-attribute-value-change``` --> mwdi-1-0-0-op-c-is-hmwdi-1-0-0-100
- ```/v1/regard-object-creation``` --> mwdi-1-0-0-op-c-is-hmwdi-1-0-0-101
- ```/v1/regard-object-deletion``` --> mwdi-1-0-0-op-c-is-hmwdi-1-0-0-102

MWDI pass through this information to HistoricalMicroWaveDeviceInventory.

Unless you are mentioning the following API:
```/v1/notify-attribute-value-changes```

where the body contains:
```
{
  "subscriber-application": "HistoricalMicrowaveDeviceInventory",
  "subscriber-release-number": "1.0.0",
  "subscriber-operation": "/v1/regard-attribute-value-change",
  "subscriber-protocol": "HTTP",
  "subscriber-address": {
    "ip-address": {
      "ipv-4-address": "1.1.4.13"
    }
  },
  "subscriber-port": 4013
}
```

**Comment by Ziabatcha** [comment]
@latta-siae , 
Actual issue observed with API "v1/regard-device-attribute-value-change "and we havent tested the API "regard-attribute-value-change".

Lookslike the confusion arose due to the prints in the docker logs. For now we will close this issue and will write a new issue for ""v1/regard-device-attribute-value-change " in 1.1.2j as its not working.
