### ISSUE TITLE
Observing error 500 when too many pending tasks in queue on load.json

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#773]
When we start the application, after sometime we are seeing below errors (too many pending tasks in queue on load.json) in docker logs. 
Version: [test_v1.0.6](https://github.com/openBackhaul/MicroWaveDeviceInventory/releases/tag/test_v1.0.6)
```
recordServiceRequest - record service request with body {} failed with error: Too many pending tasks in queue ./database/load.json
Error: Too many pending tasks in queue ./database/load.json
    at AsyncLock.acquire (/home/openbackhaul/microWaveDeviceInventory/node_modules/async-lock/lib/index.js:195:15)
    at Object.exports.readFromDatabaseAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/databaseDriver/JSONDriver.js:27:23)
    at Function.getLogicalTerminationPointListAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/ControlConstruct.js:32:59)
    at Function.getOperationServerUuidAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/layerProtocols/OperationServerInterface.js:197:13)
    at Function.createResponseHeader (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/rest/server/ResponseHeader.js:64:70)
    at /home/openbackhaul/microWaveDeviceInventory/controllers/IndividualServices.js:2224:51
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
GET /core-model-1-4:network-control-domain=live/control-construct=CO02060/logical-termination-point=LTP-ETHERNETCONTAINER-TTP-7-2/layer-protocol=LP-ETHERNETCONTAINER-TTP-7-2/wire-interface-2-0:wire-interface-pac/wire-interface-historical-performances 500 5.096 ms - 55
```
```
Errore nella chiamata REST per il dispositivo undefined: Too many pending tasks in queue ./database/load.json
Error: Too many pending tasks in queue ./database/load.json
    at AsyncLock.acquire (/home/openbackhaul/microWaveDeviceInventory/node_modules/async-lock/lib/index.js:195:15)
    at Object.exports.readFromDatabaseAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/databaseDriver/JSONDriver.js:27:23)
    at Function.getForwardingDomainListAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/ControlConstruct.js:22:32)
    at Function.getForwardingConstructListAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/ForwardingDomain.js:23:59)
    at Function.getForwardingConstructForTheForwardingNameAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/ForwardingDomain.js:75:62)
    at resolveApplicationNameAndHttpClientLtpUuidFromForwardingName (/home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:8929:54)
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:4765:50
    at new Promise (<anonymous>)
    at Object.exports.getLiveControlConstruct (/home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:4762:10)
    at sendRequest (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/CyclicProcessService/cyclicProcess.js:33:44)
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ret' of undefined
    at manageResponse (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/CyclicProcessService/cyclicProcess.js:221:24)
    at /home/openbackhaul/microWaveDeviceInventory/service/individualServices/CyclicProcessService/cyclicProcess.js:282:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4758)
 
callback : http://x.x.x.x:xxxx/rests/data/network-topology:network-topology/topology=topology-netconf/node=223270211/yang-ext:mount/core-model-1-4:control-construct header :{"Authorization":"xxxxxxxxxxxxxxxxxxx="}body :""response code:200
Error: Too many pending tasks in queue ./database/load.json
    at AsyncLock.acquire (/home/openbackhaul/microWaveDeviceInventory/node_modules/async-lock/lib/index.js:195:15)
    at Object.exports.readFromDatabaseAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/databaseDriver/JSONDriver.js:27:23)
    at Function.getLogicalTerminationPointAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/onfModel/models/ControlConstruct.js:58:59)
    at getEsClientConfigAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/services/ElasticsearchService.js:427:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getIndexAliasAsync (/home/openbackhaul/microWaveDeviceInventory/node_modules/onf-core-model-ap/applicationPattern/services/ElasticsearchService.js:478:31)
    at async recordRequest (/home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:9144:20)
    at async /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:4794:33
```

**Comment by Ziabatcha** [comment]
After setting the configuration on elastic search, issue not observed
