### ISSUE TITLE
[NotificationService] Observing 500 internal error when notification received on API:/v1/regard-device-object-deletion

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#831]
When Object delete notification is received on API:/v1/regard-device-object-deletion, observing error 500 in MWDI.
```
{"notification-proxy-1-0:object-deletion-notification":{"counter":8,"timestamp":"2024-01-29T08:25:23.0+00:00","object-path":"/core-model-1-4:network-control-domain=live/control-construct=513250009/forwarding-domain=VLAN-FD/fc=VLAN-3301"}}
```

**Comment by Ziabatcha** [comment]
Tested with Test_v1.1.2 , Issue is no longer observed .
For object delete notification observing 204 response.

```
{"notification-proxy-1-0:object-deletion-notification":{
"counter":6,
"timestamp":"2024-02-09T06:02:07.0+00:00",
"object-path":"/core-model-1-4:network-control-domain=live/control-construct=513250009/forwarding-domain=VLAN-FD/fc=VLAN-3301"
}
}

```

**Comment by Ziabatcha** [comment]
Same issue observing in tag:1.1.3, hence re-opened this issue.

**Comment by Ziabatcha** [comment]
Issue still observed with test_1.1.4


{"notification-proxy-1-0:object-deletion-notification":{"counter":1,"timestamp":"2024-03-18T06:44:16.0+00:00","object-path":"/core-model-1-4:network-control-domain=live/control-construct=513250009/forwarding-domain=VLAN-FD/fc=VLAN-3319"}}


2024-03-18T06:48:39.572573455Z [18.03.2024 06:48.39.572] [ERROR] TypeError: Cannot read properties of null (reading 'uuid')

2024-03-18T06:48:39.572606325Z     at /home/openbackhaul/microWaveDeviceInventory/service/individualServices/cacheUpdateBuilder.js:31:17

2024-03-18T06:48:39.572611435Z     at Array.findIndex (<anonymous>)

2024-03-18T06:48:39.572614825Z     at Object.exports.cacheUpdateBuilder (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/cacheUpdateBuilder.js:30:52)

2024-03-18T06:48:39.572617815Z     at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:9844:35

2024-03-18T06:48:39.572626275Z     at runMicrotasks (<anonymous>)

2024-03-18T06:48:39.572629205Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)

2024-03-18T06:48:39.577491044Z POST /v1/regard-device-object-deletion 500 31.747 ms - 55

2024-03-18T06:48:39.651709293Z [18.03.2024 06:48.39.651] [LOG]

2024-03-18T06:48:39.651731773Z  callback : POST http://xxx:xxx/v1/record-service-request header :{"user":"User Name","originator":"MicroWaveDeviceInventory","x-correlator":"Eee34c6E-5768-0951-5864-6272A3fF8ef0","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"Resolver","application-name":"MicroWaveDeviceInventory","release-number":"1.1.0","operation-name":"/v1/regard-device-object-deletion","response-code":500}response code:204

2024-03-18T06:49:51.870939436Z [18.03.2024 06:49.51.870] [LOG]

**Comment by Ziabatcha** [comment]
Still seeing this issue in 1.1.2.f_impl
logs:
[12.07.2024 08:45.36.658] [ERROR] NotFoundError: Field "fc"="VLAN-1004" not found in cache
    at Object.exports.cacheUpdateBuilder (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/cacheUpdateBuilder.js:53:17)
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:10373:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
POST /v1/regard-device-object-deletion 404 59.649 ms - 79
[12.07.2024 08:45.36.724] [LOG]
 callback : POST http://172.28.127.10:3003/v1/record-service-request header :{"user":"NotificationProxy","originator":"MicroWaveDeviceInventory","x-correlator":"f0776C42-FEeb-0A3b-7ACe-51edaEF20CCa","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"21B1bdaa-D69B-70f5-4C7f-2c01aF476fBd","trace-indicator":"1","user":"NotificationProxy","originator":"NotificationProxy","application-name":"MicroWaveDeviceInventory","release-number":"1.1.0","operation-name":"/v1/regard-device-object-deletion","response-code":404}response code:204

**Comment by Ziabatcha** [comment]
Tested with latest  MWDI version 1.1.2.g_impl, Issue is no longer observed.

Object Deletion:
````
http://XXXXX:XXXX/v1/regard-device-object-deletion
 
{"notification-proxy-1-0:object-deletion-notification":{"counter":1,"timestamp":"2024-10-14T07:17:22.0+00:00","object-path":"/core-model-1-4:network-control-domain=live/control-construct=513250009/forwarding-domain=VLAN-FD/fc=VLAN-3387"}}
 `````
Response : 204 OK
