### ISSUE TITLE
Observing error in MWDI docker logs for fd-status,number-of-static-entries-cur attributes.

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#927]
Observing error in MWDI docker logs for fd-status,number-of-static-entries-cur attributes.
Version:[1.1.0.a_impl](https://github.com/openBackhaul/MicroWaveDeviceInventory/releases/tag/1.1.0.a_impl)

Logs:
```
 callback : POST X.X.X.X:XXXX/v1/record-service-request header :{"user":"User Name","originator":"MicroWaveDeviceInventory","x-corr8E-a7cF-89C5-2C4c3fD1aBdd","trace-indicator":1,"customer-journey":"unknown","operation-key":"-----","Content-Type":"ap :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"MacAddressTableRecorder","aproWaveDeviceInventory","release-number":"1.1.0","operation-name":"/core-model-1-4:network-control-domain=cache/control-construct=513559991A?fiel%28uuid%3Blayer-protocol-name%3Bmac-fd-1-0%3Amac-fd-pac%28mac-fd-status%28mac-address-cur%29%29%29","response-code":500}response code:204
[14.04.2024 00:04.12.701] [LOG]
 callback : POST X.X.X.X:XXXX/v1/record-service-request header :{"user":"User Name","originator":"MicroWaveDeviceInventory","x-corr4B-f8ca-b4dB-C99b0447F2C4","trace-indicator":1,"customer-journey":"unknown","operation-key":"-----","Content-Type":"ap :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"MacAddressTableRecorder","aproWaveDeviceInventory","release-number":"1.1.0","operation-name":"/core-model-1-4:network-control-domain=cache/control-construct=CO02060?fields=uuid%3Blayer-protocol-name%3Bmac-fd-1-0%3Amac-fd-pac%28mac-fd-status%28mac-address-cur%29%29%29","response-code":500}response code:204
[14.04.2024 00:04.12.712] [LOG]
 callback : POST X.X.X.X:XXXX/v1/record-service-request header :{"user":"User Name","originator":"MicroWaveDeviceInventory","x-corr2c-a377-77c4-1e586c34000C","trace-indicator":1,"customer-journey":"unknown","operation-key":"-----","Content-Type":"ap :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"MacAddressTableRecorder","aproWaveDeviceInventory","release-number":"1.1.0","operation-name":"/core-model-1-4:network-control-domain=cache/control-construct=CO13305?fields=uuid%3Blayer-protocol-name%3Bmac-fd-1-0%3Amac-fd-pac%28mac-fd-status%28mac-address-cur%29%29%29","response-code":500}response code:204
[14.04.2024 00:04.12.739] [ERROR] TypeError: Cannot set properties of undefined (setting 'number-of-static-entries-cur')
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:188:41)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:193:25)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:176:29)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:176:29)
    at Object.exports.getFilteredJsonExt (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:202:12)
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:1049:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[14.04.2024 00:04.12.843] [ERROR] TypeError: Cannot set properties of undefined (setting 'number-of-static-entries-cur')
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:188:41)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:193:25)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:176:29)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:176:29)
    at Object.exports.getFilteredJsonExt (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:202:12)
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:1049:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[14.04.2024 00:04.12.860] [ERROR] TypeError: Cannot set properties of undefined (setting 'fd-status')
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:188:41)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:193:25)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:176:29)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:176:29)
    at Object.exports.getFilteredJsonExt (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:202:12)
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:1049:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[14.04.2024 00:04.12.950] [ERROR] TypeError: Cannot set properties of undefined (setting 'number-of-static-entries-cur')
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:188:41)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:193:25)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:176:29)
    at getFilteredJson (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:176:29)
    at Object.exports.getFilteredJsonExt (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/fieldsManagement.js:202:12)
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:1049:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[14.04.2024 00:04.12.951] [LOG]
```

**Comment by Ziabatcha** [comment]
Tested with latest pkg 1.1.2a_impl. Issue is not observed hence closing .
