### ISSUE TITLE
[Ops] observing 500 internal server error in docker logs

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#947]
Observing 500 internal server in docker logs, but unable to locate the for which request these "500 Internal servers" error is observed. 

version:[1.1.2.a_impl](https://github.com/openBackhaul/MicroWaveDeviceInventory/releases/tag/1.1.2.a_impl)

Logs:
```
[26.04.2024 07:03.21.402] [LOG]   [Resp. Time: 12384ms] Response from element 513250013. Dropped from S-W. Add element CO13306 in S-W and send request...
[26.04.2024 07:03.21.447] [LOG]
 callback : POST http://x.x.x.x:xxxx/v1/record-service-request header :{"user":"MicroWaveDeviceInventory","originator":"MicroWaveDeviceInventory","x-correlator":"C547faec-aC99-423E-dCaC-E1c6A326C191","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"C31f9174-cb3e-6Dfe-eCBe-8EBFBd6Dc709","trace-indicator":"1","user":"MicroWaveDeviceInventory","originator":"MicroWaveDeviceInventory","application-name":"MicroWaveDeviceInventory","release-number":"1.1.0","operation-name":"/core-model-1-4:network-control-domain=live/control-construct=513250013","response-code":200}response code:204
^[[0mGET /core-model-1-4:network-control-domain=cache/control-construct=CO13306/logical-termination-point=CO13306+LTP-MAC-TTP-SLOT-02-LIM_LAN-2-RJ45/ltp-augment-1-0:ltp-augment-pac?fields=original-ltp-name ^[[32m200^[[0m 60.815 ms - 79^[[0m
^[[0mGET /core-model-1-4:network-control-domain=cache/control-construct=CO13306/logical-termination-point=CO13306+LTP-MAC-TTP-RLAG-1/ltp-augment-1-0:ltp-augment-pac?fields=original-ltp-name ^[[32m200^[[0m 61.300 ms - 92^[[0m
^[[0mGET /core-model-1-4:network-control-domain=cache/control-construct=CO13306/logical-termination-point=CO13306+LTP-MAC-TTP-SLOT-02-LIM_LAN-5-SFP/ltp-augment-1-0:ltp-augment-pac?fields=original-ltp-name ^[[32m200^[[0m 71.978 ms - 79^[[0m
[26.04.2024 07:03.23.702] [LOG]
 callback : POST http://x.x.x.x:xxxx/v1/record-service-request header :{"user":"User Name","originator":"MicroWaveDeviceInventory","x-correlator":"B6f9D0B7-0b82-fE3e-CBEA-Caf251d8bcD1","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"Resolver","application-name":"MicroWaveDeviceInventory","release-number":"1.1.0","operation-name":"/core-model-1-4:network-control-domain=cache/control-construct=CO13306/logical-termination-point=CO13306+LTP-MAC-TTP-SLOT-02-LIM_LAN-2-RJ45/ltp-augment-1-0:ltp-augment-pac?fields=original-ltp-name","response-code":200}response code:204
[26.04.2024 07:03.23.703] [LOG]
 callback : POST http://x.x.x.x:xxxx/v1/record-service-request header :{"user":"User Name","originator":"MicroWaveDeviceInventory","x-correlator":"3ca7fF4A-eCBD-dEce-3f2B-FfCA2ABA3787","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"Resolver","application-name":"MicroWaveDeviceInventory","release-number":"1.1.0","operation-name":"/core-model-1-4:network-control-domain=cache/control-construct=CO13306/logical-termination-point=CO13306+LTP-MAC-TTP-RLAG-1/ltp-augment-1-0:ltp-augment-pac?fields=original-ltp-name","response-code":200}response code:204
^[[0mGET /core-model-1-4:network-control-domain=cache/control-construct=513250010/logical-termination-point=513250010+MAC-2134647012/ltp-augment-1-0:ltp-augment-pac?fields=original-ltp-name ^[[32m200^[[0m 26.953 ms - 85^[[0m
[26.04.2024 07:03.34.193] [LOG]
 callback : POST http://x.x.x.x:xxxx/v1/record-service-request header :{"user":"User Name","originator":"MicroWaveDeviceInventory","x-correlator":"EC9Fff41-369e-4Bd8-53CE-712bE968Ae1a","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"Resolver","application-name":"MicroWaveDeviceInventory","release-number":"1.1.0","operation-name":"/core-model-1-4:network-control-domain=cache/control-construct=513250010/logical-termination-point=513250010+MAC-2134647012/ltp-augment-1-0:ltp-augment-pac?fields=original-ltp-name","response-code":200}response code:204
[26.04.2024 07:04.00.946] [ERROR] InternalServerError: Internal Server Error
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:5559:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[26.04.2024 07:04.00.946] [LOG]   [Resp. Time: 55017ms] Response from element CO15338. Dropped from S-W. Add element 513559991B in S-W and send request...

```

**Comment by Ziabatcha** [comment]
Issue cross checked in 1.1.2.i_impl, still seeing the issue in docker logs. 
Observing "InternalServerError" error and unable to check for which request this error message is throwing in docker logs.

```
 callback : POST http://10.20.64.41:3003/v1/record-service-request header :{"user":"User Name","originator":"MicroWaveDeviceInventory","x-correlator":"3AAC8aAf-716C-3aeF-e03F-d2c8f183F8BD","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"MacAddressTableRecorder","application-name":"MicroWaveDeviceInventory","release-number":"1.1.0","operation-name":"/core-model-1-4:network-control-domain=cache/control-construct=427252246?fields=forwarding-domain%28uuid%3Blayer-protocol-name%3Bmac-fd-1-0%3Amac-fd-pac%28mac-fd-status%28mac-address-cur%29%29%29","response-code":200,"timestamp":"2024-12-18T10:03:54+00:00"}response code:204
[18.12.2024 10:03.54.707] [ERROR] InternalServerError: Internal Server Error
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:11921:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5
```

**Comment by latta-siae** [comment]
Note for developers:
to be investigate in "getLiveControlConstructFromSW"
to be check mountname double references. could be empty. 
This function is recall in cycle loop

**Comment by latta-siae** [comment]
yes as I explain the latest meeting. I have enrich the log.
So could be useful to share the log when the error appears.

**Comment by Ziabatcha** [comment]
Tested with 1.1.2.k_impl
Attaching the logs:
```
[03.06.2025 07:06.12.623] [ERROR] InternalServerError: Internal Server Error
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:11933:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[03.06.2025 07:06.12.624] [LOG]   [Resp. Time: 932037ms] Response from element CO06250 not more present in S-W. Ignore that.
[03.06.2025 07:06.12.737] [LOG]
```

**Comment by PrathibaJee** [comment]
@zaia-siae , kindly please close this issue if the latest logs are as per the expectation.

**Comment by latta-siae** [comment]
Yes this expected behaviour during cycleprocess

**Comment by Ziabatcha** [comment]
Tested with v1.2.2-hotfix.1_impl and understand that these prints are for developers.
