### ISSUE TITLE
[Ops] observing Bad request error message in docker logs without any information on what caused bad request.

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#974]
observing Bad request error message in docker logs without any information on what caused bad request.

Version:[1.1.2.d_impl](https://github.com/openBackhaul/MicroWaveDeviceInventory/tree/1.1.2.d_impl)

Logs:
```
[27.05.2024 06:45.46.592] [ERROR] BadRequestError: Bad Request
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:4681:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[27.05.2024 06:45.47.203] [ERROR] BadRequestError: Bad Request
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:4681:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Ziabatcha** [comment]
@latta-siae , any update on this issue ?

**Comment by Ziabatcha** [comment]
Same issue already reported [947](https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/947) , hence closing this issue

**Comment by latta-siae** [comment]
This issue is different from the #947 
Bad request is thrown when ELK has been queried and result is empty.

**Comment by latta-siae** [comment]
Added log in order to understand which part of the code fails

**Comment by Ziabatcha** [comment]
Tested with latest package 1.1.2.l_impl still we observing "Bad Request" in docker logs.

Please find the logs
```
[07:14:03.402] INFO (1): Control Construct - Read from ELK mountname: 513250013
[07:14:03.703] INFO (1): Control Construct - Read from ELK mountname: CO06250
GET /core-model-1-4:network-control-domain=cache/control-construct=CO06250?fields=forwarding-domain%28uuid%3Blayer-protocol-name%3Bmac-fd-1-0%3Amac-fd-pac%28mac-fd-status%28mac-address-cur%29%29%29 200 170.058 ms - 939
[12.06.2025 07:14.03.982] [LOG]
 callback : POST http://172.28.127.18:3033/v1/record-service-request header :{"user":"MacAddressTableRecorder","originator":"MicroWaveDeviceInventory","x-correlator":"4ab38C9B-d394-D508-2dCb-5Cf9E034ac55","trace-indicator":"1","customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"358EbE52-c048-6ece-b29e-3CB7BC597Dc6","trace-indicator":"1","user":"MacAddressTableRecorder","originator":"MacAddressTableRecorder","application-name":"MicroWaveDeviceInventory","release-number":"1.1.2","operation-name":"/core-model-1-4:network-control-domain=cache/control-construct=CO06250?fields=forwarding-domain%28uuid%3Blayer-protocol-name%3Bmac-fd-1-0%3Amac-fd-pac%28mac-fd-status%28mac-address-cur%29%29%29","response-code":200,"timestamp":"2025-06-12T07:14:03+00:00"}response code:204
[07:14:03.996] INFO (1): LTP Augmented - Read from ELK mountname: 513250013
[07:14:04.006] WARN (1): Ltp Augment: JSON is empty, throwing BAD_REQUEST
[07:14:04.006] ERROR (1): Bad Request
    err: {
      "type": "BadRequestError",
      "message": "Bad Request",
      "stack":
          BadRequestError: Bad Request
              at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:5033:21
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "status": 400,
      "statusCode": 400,
      "expose": true
    }
GET /core-model-1-4:network-control-domain=cache/control-construct=513250013/logical-termination-point=513250013+mac-gei-1-1-0-5/ltp-augment-1-0:ltp-augment-pac?fields=original-ltp-name 400 75.012 ms - 45

```
We are assuming that when the ELK/ODL has been queried and result is empty it will throw bad request error.
Could you please clarify on this?

**Comment by latta-siae** [comment]
Hi @Ziabatcha,

basically it is saying in the cache (ELK) for mountname 513250013 fails
on the request that is
/core-model-1-4:network-control-domain=cache/control-construct=513250013/logical-termination-point=513250013+mac-gei-1-1-0-5/ltp-augment-1-0:ltp-augment-pac?**fields=original-ltp-name**

probably this section is empty.
could try to manually check the cache using elastic?

**Comment by PrathibaJee** [comment]
@Ziabatcha Kindly please clarify the following doubt,
1. After observing the error messages in the logs, is there any major consequence we are facing in MWDI ?

**Comment by latta-siae** [comment]
This request probably come from MATR looking for MacAddress information.
MWDI handle the error properly.

**Comment by Ziabatcha** [comment]
Tested with Latest version 1.2.2-hotfix_impl and understand the below print is there as ltp-name is not defined from device itself.


[14.07.2025 15:38.38.366] [ERROR] BadRequestError: Resource not existing. Device informs about addressed resource unknown
    at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:2955:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  expose: true,
  statusCode: 470,
  status: 470
}
GET /core-model-1-4:network-control-domain=cache/control-construct=513250013/logical-termination-point=513250013+mac-gei-1-1-0-5/ltp-augment-1-0:ltp-augment-pac?fields=original-ltp-name 470 41.702 ms - 104
GET /core-model-1-4:network-control-domain=cache/control-construct=CO12996?fields=forwarding-domain%28uuid%3Blayer-protocol-name%3Bmac-fd-1-0%3Amac-fd-pac%28mac-fd-status%28mac-address-cur%29%29%29 200 268.389 ms - 2708
[14.07.2025 15:38.38.774] [LOG]

[15:38:38.367] ERROR (1): Resource not existing. Device informs about addressed resource unknown
    err: {
      "type": "BadRequestError",
      "message": "Resource not existing. Device informs about addressed resource unknown",
      "stack":
          BadRequestError: Resource not existing. Device informs about addressed resource unknown
              at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:2955:21
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "expose": true,
      "statusCode": 470,
      "status": 470
    }
