### ISSUE TITLE
[Ops] MWDI is stopped during realignment process

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#988]
MWDI is stopped during realignment process and observed below error message is observed
Package: 1.1.2.e_impl

Logs:
```
2024-06-28T08:19:37.741659280Z [28.06.2024 08:19.37.741] [LOG]   
2024-06-28T08:19:37.741709940Z  callback : http://10.20.64.9:8080/rests/data/network-topology:network-topology/topology=topology-netconf/node=325254819/yang-ext:mount/core-model-1-4:control-construct header :{"Authorization":"Basic bXdkaV9yZWFkXzI6TVdESUA3NjU0Iw=="}body :""response code:200
2024-06-28T08:19:37.974932613Z [28.06.2024 08:19.37.974] [LOG]   
2024-06-28T08:19:37.974983383Z  callback : POST http://10.20.64.41:3003/v1/record-service-request header :{"user":"MicroWaveDeviceInventory","originator":"MicroWaveDeviceInventory","x-correlator":"F17a1098-5Ba8-D56b-8D7C-1698De5AeEC2","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"Dce0ac56-fAd3-11A5-b0cC-da2DF841d12f","trace-indicator":"1","user":"MicroWaveDeviceInventory","originator":"MicroWaveDeviceInventory","application-name":"MicroWaveDeviceInventory","release-number":"1.1.0","operation-name":"/core-model-1-4:network-control-domain=live/control-construct=325254819","response-code":200}response code:204
2024-06-28T08:19:38.329483454Z [28.06.2024 08:19.38.329] [LOG]   <Notification>  node-id: 326251458   status: connected
2024-06-28T08:19:38.338191714Z /home/openbackhaul/microWaveDeviceInventory/service/individualServices/CyclicProcessService/cyclicProcess.js:453
2024-06-28T08:19:38.338239913Z             await sleep(50);
2024-06-28T08:19:38.338243953Z             ^
2024-06-28T08:19:38.338246643Z 
2024-06-28T08:19:38.338261773Z ReferenceError: sleep is not defined
2024-06-28T08:19:38.338265204Z     at updateDeviceListFromNotification (/home/openbackhaul/microWaveDeviceInventory/service/individualServices/CyclicProcessService/cyclicProcess.js:453:13)
2024-06-28T08:19:38.338268413Z     at /home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:10106:9
2024-06-28T08:19:38.338274293Z     at new Promise (<anonymous>)
2024-06-28T08:19:38.338277753Z     at Object.exports.regardControllerAttributeValueChange (/home/openbackhaul/microWaveDeviceInventory/service/IndividualServicesService.js:10079:10)
2024-06-28T08:19:38.338281104Z     at SwaggerRouter.regardControllerAttributeValueChange (/home/openbackhaul/microWaveDeviceInventory/controllers/IndividualServices.js:2794:22)
2024-06-28T08:19:38.338284424Z     at /home/openbackhaul/microWaveDeviceInventory/node_modules/openbackhaul-oas3-tools/dist/middleware/swagger.router.js:99:40
2024-06-28T08:19:38.338308393Z     at Layer.handle [as handle_request] (/home/openbackhaul/microWaveDeviceInventory/node_modules/express/lib/router/layer.js:95:5)
2024-06-28T08:19:38.338313853Z     at trim_prefix (/home/openbackhaul/microWaveDeviceInventory/node_modules/express/lib/router/index.js:328:13)
2024-06-28T08:19:38.338316893Z     at /home/openbackhaul/microWaveDeviceInventory/node_modules/express/lib/router/index.js:286:9
2024-06-28T08:19:38.338319664Z     at Function.process_params (/home/openbackhaul/microWaveDeviceInventory/node_modules/express/lib/router/index.js:346:12)
[nq10057135_gcp_telefonica_de@mwappserver2 ~]$
```

**Comment by Ziabatcha** [comment]
Issue not observed in 1.1.2g, hence closing this issue
