### ISSUE TITLE
Observing 500 Internal server error for DEVICE Attribute value change notification API in MWDI- 1.1.2f

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MicroWaveDeviceInventory#992]
Observing 500 Internal server error for DEVICE Attribute value change notification API in MWDI 1.1.2f

API: http://XX:XX/v1/regard-device-attribute-value-change

Notification for AVC:
{"notification-proxy-1-0:attribute-value-changed-notification":{"counter":26,"timestamp":"2024-07-17T07:42:19.0+00:00","object-path":"/core-model-1-4:network-control-domain=live/control-construct=513250006/logical-termination-point=LTP-MWPS-TTP-ODU-A/layer-protocol=LP-MWPS-TTP-ODU-A/air-interface-2-0:air-interface-pac/air-interface-configuration","attribute-name":"adaptive-modulation-is-on","new-value":"true"}}

RESPONSE:

{
  "code": 500,
  "message": "Internal Server Error"
}

Docker Logs:

 callback : POST http://xx:xx/v1/record-service-request header :{"user":"NotificationProxy","originator":"NotificationProxy","x-correlator":"DDc0E22a-855f-39ce-B9D5-ca5020fEDedB","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"19d24E6E-7c2c-bFcA-C6c0-7ba8B8ffB3f1","trace-indicator":"1","user":"NotificationProxy","originator":"NotificationProxy","application-name":"NotificationProxy","release-number":"1.0.1","operation-name":"/v1/notify-device-attribute-value-changes","response-code":500}response code:204
[07:42:21.037] ERROR (1): error during subscriber-notification for /v1/notify-device-attribute-value-changes - debugId: 'e5f41d57-a63d-4332-978d-6739c6c2063a'
    err: {
      "message": "Request failed with status code 500",
      "name": "AxiosError",
      "stack":
          AxiosError: Request failed with status code 500
              at settle (/home/openbackhaul/NotificationProxy/node_modules/axios/dist/node/axios.cjs:1913:12)
              at IncomingMessage.handleStreamEnd (/home/openbackhaul/NotificationProxy/node_modules/axios/dist/node/axios.cjs:2995:11)
              at IncomingMessage.emit (node:events:525:35)
              at endReadableNT (node:internal/streams/readable:1358:12)
              at processTicksAndRejections (node:internal/process/task_queues:83:21)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },

        "method": "post",
        "url": "HTTP://xx:xx/v1/regard-device-attribute-value-change",
        "data": "{\"notification-proxy-1-0:attribute-value-changed-notification\":{\"counter\":26,\"timestamp\":\"2024-07-17T07:42:19.0+00:00\",\"object-path\":\"/core-model-1-4:network-control-domain=live/control-construct=513250006/logical-termination-point=LTP-MWPS-TTP-ODU-A/layer-protocol=LP-MWPS-TTP-ODU-A/air-interface-2-0:air-interface-pac/air-interface-configuration\",\"attribute-name\":\"adaptive-modulation-is-on\",\"new-value\":\"true\"}}"
      },
      "code": "ERR_BAD_RESPONSE",
      "status": 500
    }

**Comment by Ziabatcha** [comment]
Tested okay with 1.1.2g package. Issue is no longer observed.
Observing 204 for Device AVC in MWDI.


API: http://xx:XX/v1/regard-device-attribute-value-change

'''
Body:

{"notification-proxy-1-0:attribute-value-changed-notification":{"counter":21,"timestamp":"2024-09-11T08:22:12.0+00:00","object-path":"/core-model-1-4:network-control-domain=live/control-construct=513250006/logical-termination-point=LTP-MWPS-TTP-ODU-A/ltp-augment-1-0:ltp-augment-pac","attribute-name":"external-label","new-value":"513249876A"}}

 callback : POST http://172.28.127.10:3026/v1/record-service-request header :{"user":"User Name","originator":"MicroWaveDeviceInventory","x-correlator":"2D51F1BA-5fb3-848b-0352-be7dDf3cf2eb","trace-indicator":1,"customer-journey":"unknown","operation-key":"Operation key not yet provided.","Content-Type":"application/json"}body :{"x-correlator":"550e8400-e29b-11d4-a716-446655440000","trace-indicator":"1.3.1","user":"User Name","originator":"Resolver","application-name":"MicroWaveDeviceInventory","release-number":"1.1.0","operation-name":"/core-model-1-4:network-control-domain=live/control-construct=513250006/logical-termination-point=LTP-MWPS-TTP-ODU-A/ltp-augment-1-0:ltp-augment-pac","response-code":200}response code:204
[11.09.2024 09:53.34.623] [LOG]


'''

![image](https://github.com/user-attachments/assets/5db15498-4e23-47fd-bc6d-747260c1e805)
